### ISSUE TITLE
Parseval Segmentation Fault

### ISSUE THREAD

**Issue by sagnikbanerjee15** [BrendelGroup/AEGeAn#192]
Hello,

I split my gff3 by chromosomes since the last time I tried to run them all together I encountered an error. The runs were completed without any error for most of the chromosomes. In one of the cases I got a segmentation fault. I have attached the reference and the predicted files.

This is the command I used.

chromosome=6
nohup parseval -w -x AGPv4 -y AGPv3 -f html -o AGPv4_to_AGPv3_parseval.${chromosome} Zea_mays.AGPv4.39.tidy.${chromosome}.gff3 Gene_Models_v3_to_v4.sorted.no.chr.${chromosome}.gff3 > AGPv4_to_AGPv3_parseval.${chromosome}.output 2> AGPv4_to_AGPv3_parseval.${chromosome}.error &
[ref_and_pred_chr6.zip](https://github.com/BrendelGroup/AEGeAn/files/2207014/ref_and_pred_chr6.zip)

Thank you.

**Comment by standage** [comment]
Hi again @sagnikbanerjee15, I apologize for the delay in my response. I have been busy with relocating.

Because this is a follow-up of a thread you previously posted (#190), I'm going to copy your post back to the original thread, close this new thread, and continue discussion on the original thread.
